### ISSUE TITLE
What ogre version is this meant to build with?

### ISSUE THREAD

**Issue by paulie-g** [darksylinc/colibrigui#61]
I've built the recommended ogre-next 2.2 and get a lot of missing symbols whose declarations are behind ifdefs looking for OGRE_MAKE > 3.

**Comment by darksylinc** [comment]
Hi!

Sorry for the delay.

It should support 2.3, 3.0 and 4.0

I just checked and it seems 2.2 build was broken recently. I'll fix it, however the new feature `OffScreenCanvas` won't be available.

**Comment by darksylinc** [comment]
[Done](https://github.com/darksylinc/colibrigui/commit/ed1a9978299265a6573a3f7819a5e3b36073aa68).

**Comment by paulie-g** [comment]
Thank you. This still fails to build with 2.2:
```
/home/paul/dev/gui/colibrigui/src/ColibriGui/Text/ColibriBmpFont.cpp:213:48: error: aggregate ‘Ogre::HlmsSamplerblock samplerblock’ has incomplete type and cannot be defined
  213 |                         Ogre::HlmsSamplerblock samplerblock;
```

Building with 2.3.3 succeeds, but the main demo fails to run when it can't resolve 
```An exception has occured: OGRE EXCEPTION(7:InternalErrorException): Could not load dynamic library Plugins/RenderSystem_Vulkan.  System Error: Plugins/RenderSystem_Vulkan.so.2.3.3: undefined symbol: _ZN7glslang8TProgram10getInfoLogEv in DynLib::load at /home/paul/dev/gui/ogre-total/ogre-next-2.3.3/OgreMain/src/OgreDynLib.cpp (line 111)```

The above might be some sort of local problem with the ogre build. I'd prefer to build with the distro-provided ogre-next 2.3.3, which is available to me in Arch's extra repo, but the build process doesn't seem to want to do pkg-config to find it.

Managed to build with ogre-next master, although I had to patch some of its deps with missing includes for `<cstdint>`. Vulkan backend doesn't work for me either in ogre's own tests or in colibri with:
```
An exception has occured: OGRE EXCEPTION(3:RenderingAPIException): Fragment Program 300000000PixelShader_ps failed to compile. See compile log above for details. in VulkanProgram::compile at /home/paul/dev/gui/ogre-total/ogre-master/Ogre/ogre-next/RenderSystems/Vulkan/src/OgreVulkanProgram.cpp (line 751)
```

However, disabling Vulkan in the plugins.cfg and choosing OpenGL does work. So, at least I got this to build with something.

**Comment by darksylinc** [comment]
Hi!

It seems there is an ABI mismatch/confusion with the glslang compiler in your system and the one used to compile & link OgreNext and thus everything went sideways after that.

This shouldn't happen if OgreNext dependencies were obtained from [ogre-next-deps](https://github.com/OGRECave/ogre-next-deps)

We recommend using the [Quick Start scripts](https://github.com/OGRECave/ogre-next?tab=readme-ov-file#quick-start) to avoid this kind of issues.

**Comment by paulie-g** [comment]
While that may be true for the build using 2.3.3, I ran the build with current git master using the build-latest quick start script, albeit having edited in the RelWithDebInfo target, which colibri's build seems to have hardcoded in.
